### ISSUE TITLE
Secret key snippet doesn't works in Django 1.8.5

### ISSUE THREAD

**Issue by SalahAdDin** [springload/madewithwagtail#16]
When i try use ./manage.py shell say me this:

```bash
server)tulipanrog@tulipanrog-G771JW:/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/commands/syncdb.py", line 4, in <module>
    from django.contrib.auth import get_user_model
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
(server)tulipanrog@tulipanrog-G771JW:/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/commands/syncdb.py", line 4, in <module>
    from django.contrib.auth import get_user_model
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
(server)tulipanrog@tulipanrog-G771JW:/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/commands/syncdb.py", line 4, in <module>
    from django.contrib.auth import get_user_model
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
(server)tulipanrog@tulipanrog-G771JW:/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/management/commands/syncdb.py", line 4, in <module>
    from django.contrib.auth import get_user_model
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

Why happen this?

**Comment by jordij** [comment]
Those errors seem to come from running `manage.py syncdb` and not `manage.py shell`.

And they seem to come from a different project too? We set the `SECRET_KEY` in the `base.py` settings. You might wanna have a look at your settings to double check you have `SECRET_KEY` properly set.

I'm closing this one as I understand it doesn't apply to this project.
